verbatim:
  cabal-version: 2.2

name: duet
version: 0.0.0.0

default-extensions:
  - ConstraintKinds
  - DataKinds
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadComprehensions
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - RebindableSyntax
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - StrictData
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - UndecidableSuperClasses
  - UnicodeSyntax
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wno-orphans
  - -Wno-partial-type-signatures
  - -j
  - -O0
  - -threaded -rtsopts -with-rtsopts=-N 

dependencies:
  - base
  - uvmhs
  - random
  - mwc-random
  - time
  - normaldistribution >= 1.1.0.3

library:
  source-dirs: src

executable:
  source-dirs: main
  main: Main.hs
  dependencies: duet
